/**
 * SlyderChat design tokens — ported from slyder_chat_UI/ios_messaging_standard/DESIGN.md.
 * `light` is the token set exported from the design file verbatim. `dark` is a hand-tuned
 * Material 3 dark scheme built from the same seed: fixed/on-*-container roles are reused
 * per the M3 role-mapping convention (e.g. dark.primary = light.primaryFixedDim), and
 * surfaces drop to true OLED black per the DESIGN.md "Dark Mode" note.
 */

export type ColorScheme = { [K in keyof typeof light]: string };

export const light = {
  surface: '#faf9fe',
  surfaceDim: '#dad9df',
  surfaceBright: '#faf9fe',
  surfaceContainerLowest: '#ffffff',
  surfaceContainerLow: '#f4f3f8',
  surfaceContainer: '#eeedf3',
  surfaceContainerHigh: '#e9e7ed',
  surfaceContainerHighest: '#e3e2e7',
  onSurface: '#1a1b1f',
  onSurfaceVariant: '#3c4a3d',
  inverseSurface: '#2f3034',
  inverseOnSurface: '#f1f0f5',
  outline: '#6c7b6b',
  outlineVariant: '#bbcbb9',
  surfaceTint: '#006d2f',
  primary: '#006d2f',
  onPrimary: '#ffffff',
  primaryContainer: '#25d366',
  onPrimaryContainer: '#005523',
  inversePrimary: '#3de273',
  secondary: '#1c695f',
  onSecondary: '#ffffff',
  secondaryContainer: '#a5ede0',
  onSecondaryContainer: '#226e63',
  tertiary: '#93492e',
  onTertiary: '#ffffff',
  tertiaryContainer: '#ffa07e',
  onTertiaryContainer: '#78351b',
  error: '#ba1a1a',
  onError: '#ffffff',
  errorContainer: '#ffdad6',
  onErrorContainer: '#93000a',
  primaryFixed: '#66ff8e',
  primaryFixedDim: '#3de273',
  onPrimaryFixed: '#002109',
  onPrimaryFixedVariant: '#005322',
  secondaryFixed: '#a8f0e3',
  secondaryFixedDim: '#8cd4c7',
  onSecondaryFixed: '#00201c',
  onSecondaryFixedVariant: '#005047',
  tertiaryFixed: '#ffdbcf',
  tertiaryFixedDim: '#ffb59b',
  onTertiaryFixed: '#380d00',
  onTertiaryFixedVariant: '#763319',
  background: '#faf9fe',
  onBackground: '#1a1b1f',
  surfaceVariant: '#e3e2e7',

  // App-specific extensions (not part of the raw M3 export)
  chatWallpaper: '#efe7de',
  bubbleOut: '#25d366',
  onBubbleOut: '#005523',
  bubbleIn: '#ffffff',
  onBubbleIn: '#1a1b1f',
  readTick: '#34b7f1',
  grouped: '#f2f2f7',
} as const;

export const dark = {
  surface: '#000000',
  surfaceDim: '#000000',
  surfaceBright: '#38393d',
  surfaceContainerLowest: '#000000',
  surfaceContainerLow: '#17181b',
  surfaceContainer: '#1e2022',
  surfaceContainerHigh: '#292a2d',
  surfaceContainerHighest: '#343538',
  onSurface: '#f1f0f5',
  onSurfaceVariant: '#bbcbb9',
  inverseSurface: '#e3e2e7',
  inverseOnSurface: '#1a1b1f',
  outline: '#889287',
  outlineVariant: '#3c4a3d',
  surfaceTint: '#3de273',
  primary: '#3de273',
  onPrimary: '#00391a',
  primaryContainer: '#005523',
  onPrimaryContainer: '#66ff8e',
  inversePrimary: '#006d2f',
  secondary: '#8cd4c7',
  onSecondary: '#00382f',
  secondaryContainer: '#226e63',
  onSecondaryContainer: '#a8f0e3',
  tertiary: '#ffb59b',
  onTertiary: '#5c1e08',
  tertiaryContainer: '#78351b',
  onTertiaryContainer: '#ffdbcf',
  error: '#ffb4ab',
  onError: '#690005',
  errorContainer: '#93000a',
  onErrorContainer: '#ffdad6',
  primaryFixed: '#66ff8e',
  primaryFixedDim: '#3de273',
  onPrimaryFixed: '#002109',
  onPrimaryFixedVariant: '#005322',
  secondaryFixed: '#a8f0e3',
  secondaryFixedDim: '#8cd4c7',
  onSecondaryFixed: '#00201c',
  onSecondaryFixedVariant: '#005047',
  tertiaryFixed: '#ffdbcf',
  tertiaryFixedDim: '#ffb59b',
  onTertiaryFixed: '#380d00',
  onTertiaryFixedVariant: '#763319',
  background: '#000000',
  onBackground: '#e3e2e7',
  surfaceVariant: '#3c4a3d',

  chatWallpaper: '#0b141a',
  bubbleOut: '#005c4b',
  onBubbleOut: '#e9edeb',
  bubbleIn: '#1e2428',
  onBubbleIn: '#e9edeb',
  readTick: '#53bdeb',
  grouped: '#000000',
} satisfies ColorScheme;

/** Decorative flat icon-badge colors used in Settings-style grouped rows (from the mockups). */
export const badgeColors = {
  yellow: '#ffd600',
  blue: '#007aff',
  green: '#34c759',
  red: '#ff3b30',
  pink: '#ff2d55',
  purple: '#af52de',
} as const;
