/**
 * The original mockups use Google "Material Symbols Outlined" ligature names throughout.
 * expo-symbols renders SF Symbols on iOS and Material Symbols on Android/web natively, so
 * Android/web can reuse the mockup names verbatim — only an iOS (SF Symbol) equivalent needs
 * to be supplied per icon. Unmapped names fall back to attempting the same string on iOS,
 * which works for a handful of nouns that happen to overlap (e.g. "star", "lock").
 */
export const SF_SYMBOL_MAP: Record<string, string> = {
  search: 'magnifyingglass',
  edit_square: 'square.and.pencil',
  photo_camera: 'camera',
  archive: 'archivebox',
  push_pin: 'pin.fill',
  done_all: 'checkmark.circle.fill',
  done: 'checkmark',
  groups: 'person.2.fill',
  group: 'person.2.fill',
  chat: 'bubble.left.fill',
  call: 'phone.fill',
  call_made: 'arrow.up.right',
  call_received: 'arrow.down.left',
  update: 'circle.dashed',
  circle_notifications: 'bell.badge.fill',
  settings: 'gearshape.fill',
  chevron_left: 'chevron.left',
  chevron_right: 'chevron.right',
  expand_more: 'chevron.down',
  expand_less: 'chevron.up',
  videocam: 'video.fill',
  mic: 'mic.fill',
  add: 'plus',
  add_circle: 'plus.circle.fill',
  add_a_photo: 'camera.badge.ellipsis',
  sticky_note_2: 'face.smiling',
  arrow_upward: 'arrow.up',
  signal_cellular_4_bar: 'cellularbars',
  wifi: 'wifi',
  battery_full: 'battery.100',
  language: 'globe',
  key: 'key.fill',
  lock: 'lock.fill',
  notifications: 'bell.fill',
  data_usage: 'chart.pie.fill',
  help: 'questionmark.circle.fill',
  favorite: 'heart.fill',
  star: 'star.fill',
  star_outline: 'star',
  laptop_mac: 'laptopcomputer',
  devices: 'display.and.arrow.down',
  backspace: 'delete.left',
  sms: 'message.fill',
  campaign: 'megaphone.fill',
  qr_code_2: 'qrcode',
  close: 'xmark',
  cancel: 'xmark.circle.fill',
  more_vert: 'ellipsis',
  block: 'hand.raised.fill',
  report: 'exclamationmark.bubble.fill',
  logout: 'rectangle.portrait.and.arrow.right',
  person_add: 'person.badge.plus',
  person: 'person.fill',
  group_add: 'person.2.badge.plus',
  fingerprint: 'touchid',
  timer: 'timer',
  bar_chart: 'chart.bar.fill',
  network_cell: 'antenna.radiowaves.left.and.right',
  travel_explore: 'safari.fill',
  delete: 'trash.fill',
  delete_forever: 'trash.fill',
  info: 'info.circle.fill',
  chevron_forward: 'chevron.right',
  emoji_emotions: 'face.smiling',
  image: 'photo.fill',
  description: 'doc.fill',
  mail: 'envelope.fill',
  vpn_key: 'key.fill',
  security: 'lock.shield.fill',
  storage: 'internaldrive.fill',
  wallpaper: 'photo.on.rectangle.angled',
  save: 'square.and.arrow.down',
  file_download: 'arrow.down.circle',
  brightness_6: 'circle.lefthalf.filled',
  check: 'checkmark',
  check_circle: 'checkmark.circle.fill',
  mic_off: 'mic.slash.fill',
  volume_up: 'speaker.wave.2.fill',
  schedule: 'clock.fill',
  phone_iphone: 'iphone',
  desktop_windows: 'desktopcomputer',
};

export function sfSymbolFor(name: string): string {
  return SF_SYMBOL_MAP[name] ?? name;
}
